name: wedom
description: A Flutter app for managing digital assets and transactions.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For internationalization
    sdk: flutter
  http: ^1.2.2 # For API requests
  fl_chart: ^0.70.1 # For charts
  provider: ^6.0.5 # For state management
  carousel_slider: ^4.0.0 # For carousels
  qr_flutter: ^4.0.0 # For QR code generation

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/polices

  # Fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
